//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Ressources/Input/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c0ea1768-f5ba-4d02-82a6-15ab1382cab2"",
            ""actions"": [
                {
                    ""name"": ""Fist_attack_1"",
                    ""type"": ""Button"",
                    ""id"": ""2c09fa4b-3cc8-48e2-a51d-c505ffdb1a41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fist_attack_2"",
                    ""type"": ""Button"",
                    ""id"": ""b8956d66-862e-4fed-87d2-426ddc6cdd03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Foot_attack_1"",
                    ""type"": ""Button"",
                    ""id"": ""c8688437-cda2-4637-bab7-4c30541c3c0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f5f88441-7305-434d-8647-3161e417a0d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special_attack"",
                    ""type"": ""Button"",
                    ""id"": ""7d66b6e5-5644-4307-84e5-20e5a47b4b1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""70d47017-8e73-447b-bd36-1de4a624ede6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""High_block"",
                    ""type"": ""Button"",
                    ""id"": ""13a286eb-eb4a-4f83-9847-639e300e1558"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Low_block"",
                    ""type"": ""Button"",
                    ""id"": ""0d7128ab-70bc-494a-b011-798e6e77fc3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""973e3328-209a-41b3-8ba8-2bee8924964e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cf6170c3-d58a-4667-861f-cdcb0eda8750"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Fist_attack_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2549bc25-2818-46c8-bf01-6a35bc7923b3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fist_attack_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25067f54-37f8-41a1-ba45-2c67515c04c4"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Fist_attack_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d549062-1419-4c52-a1d7-ff2353da1cf6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fist_attack_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a86d5a8e-856c-419b-a41d-e07cf7c6f6c2"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Foot_attack_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdd68b77-1554-453f-9949-8eafabdf3c0d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Foot_attack_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64e1bc30-fd7e-44eb-bf77-a01b086abaff"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14aa6ff2-edfb-47e2-a8ae-678e7eef59a5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""51423d0c-409c-4673-84bf-2d288dc89bd1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""957b5264-45d5-46ea-b787-d106d106fedc"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""728e427a-e4b9-4923-98d1-641860261eee"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""09388958-dbc1-4770-a048-2b5b9abde411"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a31c6ddd-bac8-4f91-a9a0-a69138e29e49"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""05dad5c5-a490-417d-97d1-4f3bfd049e89"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special_attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8f9a9c38-9f07-4339-ba0e-3f0ef0bbf42a"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76a3f592-ebe8-4f70-942a-2a757c55022d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd77d6bf-facd-44b4-a1b6-e1dd6eac5cca"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""High_block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c27a82b-2269-47a8-bd70-1770355f86a4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""High_block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c4efee6-64e6-42a6-873b-b86216e977ce"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Low_block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fe9f028-3d3c-439a-9b04-ebe5e8577be7"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Low_block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7ea9fb8d-faf8-46e9-ad03-a1e4a29b8796"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8a4e2492-cfae-4928-83cd-65f8d02f9a9e"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ba72b9ae-7bf8-4847-8575-ce3fd0c72c5a"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9b749c6e-5f1c-4061-bb6d-a66c88d5b1ef"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d8c16c1c-1611-456f-b262-b69d9c77dcb3"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""069e618b-85e8-4ef1-a5db-cf09154c43b8"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8055dfd9-924a-4069-bef0-e3fc5a98af68"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cc288326-d1f4-49d3-8c04-f034d15c7973"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""87a74ced-e742-4c4e-99f0-6a41282e48e1"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b126411c-a5e7-4c54-a7ad-6407b906cd29"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox"",
            ""bindingGroup"": ""Xbox"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Fist_attack_1 = m_Player.FindAction("Fist_attack_1", throwIfNotFound: true);
        m_Player_Fist_attack_2 = m_Player.FindAction("Fist_attack_2", throwIfNotFound: true);
        m_Player_Foot_attack_1 = m_Player.FindAction("Foot_attack_1", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Special_attack = m_Player.FindAction("Special_attack", throwIfNotFound: true);
        m_Player_Dodge = m_Player.FindAction("Dodge", throwIfNotFound: true);
        m_Player_High_block = m_Player.FindAction("High_block", throwIfNotFound: true);
        m_Player_Low_block = m_Player.FindAction("Low_block", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Fist_attack_1;
    private readonly InputAction m_Player_Fist_attack_2;
    private readonly InputAction m_Player_Foot_attack_1;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Special_attack;
    private readonly InputAction m_Player_Dodge;
    private readonly InputAction m_Player_High_block;
    private readonly InputAction m_Player_Low_block;
    private readonly InputAction m_Player_Movement;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fist_attack_1 => m_Wrapper.m_Player_Fist_attack_1;
        public InputAction @Fist_attack_2 => m_Wrapper.m_Player_Fist_attack_2;
        public InputAction @Foot_attack_1 => m_Wrapper.m_Player_Foot_attack_1;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Special_attack => m_Wrapper.m_Player_Special_attack;
        public InputAction @Dodge => m_Wrapper.m_Player_Dodge;
        public InputAction @High_block => m_Wrapper.m_Player_High_block;
        public InputAction @Low_block => m_Wrapper.m_Player_Low_block;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Fist_attack_1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_1;
                @Fist_attack_1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_1;
                @Fist_attack_1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_1;
                @Fist_attack_2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_2;
                @Fist_attack_2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_2;
                @Fist_attack_2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFist_attack_2;
                @Foot_attack_1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFoot_attack_1;
                @Foot_attack_1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFoot_attack_1;
                @Foot_attack_1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFoot_attack_1;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Special_attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecial_attack;
                @Special_attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecial_attack;
                @Special_attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecial_attack;
                @Dodge.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @High_block.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHigh_block;
                @High_block.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHigh_block;
                @High_block.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHigh_block;
                @Low_block.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLow_block;
                @Low_block.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLow_block;
                @Low_block.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLow_block;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Fist_attack_1.started += instance.OnFist_attack_1;
                @Fist_attack_1.performed += instance.OnFist_attack_1;
                @Fist_attack_1.canceled += instance.OnFist_attack_1;
                @Fist_attack_2.started += instance.OnFist_attack_2;
                @Fist_attack_2.performed += instance.OnFist_attack_2;
                @Fist_attack_2.canceled += instance.OnFist_attack_2;
                @Foot_attack_1.started += instance.OnFoot_attack_1;
                @Foot_attack_1.performed += instance.OnFoot_attack_1;
                @Foot_attack_1.canceled += instance.OnFoot_attack_1;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Special_attack.started += instance.OnSpecial_attack;
                @Special_attack.performed += instance.OnSpecial_attack;
                @Special_attack.canceled += instance.OnSpecial_attack;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @High_block.started += instance.OnHigh_block;
                @High_block.performed += instance.OnHigh_block;
                @High_block.canceled += instance.OnHigh_block;
                @Low_block.started += instance.OnLow_block;
                @Low_block.performed += instance.OnLow_block;
                @Low_block.canceled += instance.OnLow_block;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_XboxSchemeIndex = -1;
    public InputControlScheme XboxScheme
    {
        get
        {
            if (m_XboxSchemeIndex == -1) m_XboxSchemeIndex = asset.FindControlSchemeIndex("Xbox");
            return asset.controlSchemes[m_XboxSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnFist_attack_1(InputAction.CallbackContext context);
        void OnFist_attack_2(InputAction.CallbackContext context);
        void OnFoot_attack_1(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSpecial_attack(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnHigh_block(InputAction.CallbackContext context);
        void OnLow_block(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
    }
}
