name: Build Project
on: [push, pull_request]
jobs:
  buildOnMultiplePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
     
      #- uses: actions/cache@v3
      #  with:
      #    path: Library
      #    key: Library-${{ matrix.targetPlatform }}
      #    restore-keys: Library-

      - uses: game-ci/unity-builder@v4.0.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customImage: 'unityci/editor:2021.3.10f1-base-0'
      
      - uses: actions/upload-artifact@v3
        with:
          name: JapanFight-${{ matrix.targetPlatform }}
          path: Builds/${{ matrix.targetPlatform }}
