name: Build Project
on: [push, pull_request]
jobs:
  buildOnMultiplePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
     
     # Caching
      - uses: actions/cache@v3
        with:
          path: Library/
          key: Library-JapanFight-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-JapanFight-
            Library-

      # Build
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          #customImage: 'unityci/editor:2021.3.10f1'
      
      # Upload build 
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
