name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildOnMultiplePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Get Previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get next version
        id: next
        uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
        with:
          version: ${{ steps.previoustag.outputs.tag }}
     
      - name: Chaching Library
        uses: actions/cache@v3
        with:
          path: Library/
          key: Library-JapanFight-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-JapanFight-
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Zip artifact
        run: zip build-${{ matrix.targetPlatform }}.zip /home/runner/work/JapanFight/JapanFight/build/${{ matrix.targetPlatform }}/* -r

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ matrix.targetPlatform }}-${{ steps.next.outputs.version }}
          release_name: Release-${{ matrix.targetPlatform }}-${{ steps.next.outputs.version }}
          commitish: main
          #body_path: CHANGELOG.md # optional body (description)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-${{ matrix.targetPlatform }}.zip
          asset_name: JapanFight.zip
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ github.token }}
