name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildOnMultiplePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows
          - StandaloneWindows64
          - StandaloneLinux64
    
    # Checkout
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
     
     # Caching
      - uses: actions/cache@v3
        with:
          path: Library/
          key: Library-JapanFight-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-JapanFight-
            Library-

      # Build
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      
      # Upload build 
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      
      # Should we download the build ?
      
      # Create release
      - uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          name: ${{ steps.version.outputs.version }}
          #tag_name: ${{ github.ref }}
          #body_path: CHANGELOG.md # optional body (description)
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Upload release - Linux
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/${{ matrix.targetPlatform }}
          asset_name: Build-${{ matrix.targetPlatform }}
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      
      # Download build
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: Build-${{ matrix.targetPlatform }}
      #     path: build/${{ matrix.targetPlatform }}
      
      
      # Push artifacts
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'feat: new builds'
      #     branch: test
      #     commit_options: '--no-verify --signoff'
      #     commit_author: Author <actions@github.com>
      #     status_options: '--untracked-files=no'
      #     skip_dirty_check: false


